Improvement translation for Spanish language
stefansielaff/script.cdartmanager pull request #5
Opened 2018-05-07 18:02 UTC by roliverosc

Regards @stefansielaff

2018-05-14 11:23 UTC, stefansielaff requested changes

2018-05-14 11:23 UTC, stefansielaff commented on resources/language/Spanish/strings.po
>  "Language-Team: Spanish (Spain) (http://www.transifex.com/projects/p/cdART_Manager_XBMC_ADDON/language/es_ES/)\n"
Thanks for the awesome work! Just one little favour, could you update the line to your name here?

2018-05-27 09:22 UTC, roliverosc-zz commented on resources/language/Spanish/strings.po
>  "Language-Team: Spanish (Spain) (http://www.transifex.com/projects/p/cdART_Manager_XBMC_ADDON/language/es_ES/)\n"
Fix regards.  Sorry I had not seen it.

2018-05-28 07:43 UTC, stefansielaff approved these changes

2018-05-28 07:44 UTC, merged

2018-05-28 07:45 UTC, stefansielaff commented
Awesome, thanks :)

2018-05-28 08:11 UTC, roliverosc commented
Thank you. Regards